example_name: "vina-minimal"
model:
  path: "../../labs/vina-autodock-vina-docking-predictor/model"
  class: "src.vina_docking_predictor:VinaDockingPredictor"
  parameters:
    runtime_mode: "managed"
  inputs:
    receptor_pdbqt_path: "data/1iep/1iep_receptor.pdbqt"
    ligand_pdbqt_path: "data/1iep/1iep_ligand.pdbqt"
    run_options:
      box_center: [15.19, 53.903, 16.917]
      box_size: [20.0, 20.0, 20.0]
      exhaustiveness: 32
      n_poses: 9
      energy_range: 3.0
      cpu: 0
      scoring: "vina"
